baseURL: "https://www.covid19dataportal.se/"
title: "COVID-19 Data Portal Sweden"
params:
  title: "COVID-19 Data Portal Sweden"
  description: COVID-19 Data Portal for Swedish Research
  images:
    - /img/site_logo/CV19DP_logo_oneliner_SWE.png

  # There is a hugo i18n package, but it seems like overkill for so few strings
  lang_strings:
    en:
      home_title: Accelerating research through data sharing
      enquire_email_footer_dc: "To enquire on how to collaborate on the Swedish COVID-19 platform"
      enquire_email_footer_bioinformatics: "For bioinformatics support, please contact"
      support_feedback: Support & Feedback
      privacy: Privacy Notice
      overview: Overview
    sv:
      home_title: Snabbare forskning genom datadelning
      enquire_email_footer_dc: "För att fråga om hur man samarbetar på plattformen"
      enquire_email_footer_bioinformatics: "För support inom bioinformatik, kontakta"
      support_feedback: Support och Feedback
      privacy: Integritetspolicy
      overview: Översikt

languages:
  en:
    languageName: English
    contentDir: content/english
    weight: 1
    menu:
      top_nav:
        - name: European Hub
          url: https://www.covid19dataportal.org/
          weight: 20
      main:
        - identifier: genomics_transcriptomics_ebi_portal
          parent: genomics_transcriptomics
          name: EBI Portal
          post: <i class="fas fa-xs fa-external-link-alt"></i>
          url: 'https://www.covid19dataportal.org/sequences'
          weight: 40
        - identifier: protein_data_ebi_portal
          parent: protein_data
          name: EBI Portal
          post: <i class="fas fa-xs fa-external-link-alt"></i>
          url: 'https://www.covid19dataportal.org/proteins'
          weight: 40
        - identifier: imaging_data_ebi_portal
          parent: imaging_data
          name: EBI Portal
          post: <i class="fas fa-xs fa-external-link-alt"></i>
          url: 'https://www.covid19dataportal.org/sequences'
          weight: 40
        - identifier: compound_and_target_data_ebi_portal
          parent: compound_and_target_data
          name: EBI Portal
          post: <i class="fas fa-xs fa-external-link-alt"></i>
          url: 'https://www.covid19dataportal.org/proteins'
          weight: 40

  sv:
    languageName: Svenska
    contentDir: content/svenska
    weight: 2
    description: COVID-19 Dataportal för svensk forskning
    menu:
      top_nav:
        - name: Europeiska portalen
          url: https://www.covid19dataportal.org/
          weight: 20
      main:
        - identifier: genomics_transcriptomics_ebi_portal
          parent: genomics_transcriptomics
          name: EBI Portal
          post: <i class="fas fa-xs fa-external-link-alt"></i>
          url: 'https://www.covid19dataportal.org/sequences'
          weight: 30
        - identifier: protein_data_ebi_portal
          parent: protein_data
          name: EBI Portal
          post: <i class="fas fa-xs fa-external-link-alt"></i>
          url: 'https://www.covid19dataportal.org/proteins'
          weight: 30
